
java_tests(name = 'commons',
  sources = globs('*.java'),
  dependencies = [
    'modules/commons/src/java/com/fencedin/commons/configuration',
    'modules/commons/src/java/com/fencedin/commons/internal',
    'modules/commons/src/java/com/fencedin/commons/base',
    '3rdparty/org.apache.httpcomponents:httpclient',
    '3rdparty/org.json:json',
  ],
)
