
java_tests(name = 'gis',
  sources = globs('*.java'),

  dependencies = [
    'modules/commons/src/java/com/fencedin/commons/gis',
    'modules/commons/src/java/com/fencedin/commons/model',
    '3rdparty/junit:junit',
    '3rdparty/org.slf4j:slf4j',
    '3rdparty/com.vividsolutions:jts',
  ],

  resources=[
    'modules/commons/src/resources:log4j-properties',
  ],
)
