
java_library(name = 'database',
  dependencies = [
    '3rdparty/main/com.organization.commons:gis',
    '3rdparty/main/com.organization.commons:internal',
    '3rdparty/main/com.organization.commons:model',
    '3rdparty/main/de.undercouch:bson4jackson',
    '3rdparty/main/org.mongodb:mongodb-driver',
    '3rdparty/main/com.datastax.cassandra:cassandra-driver',
    '3rdparty/main/com.zaxxer:HikariCP',
  ],
  sources = globs('*.java'),
)
