
java_library(name = 'configuration',
  provides = artifact(
    org = 'com.fencedin.commons',
    name = 'configuration',
    repo = public,
  ),
  dependencies = [
    'modules/commons/src/java/com/fencedin/commons/base',
    '3rdparty/org.json:json',
    '3rdparty/org.slf4j:slf4j',
  ],
  sources = globs('*.java'),
)
