
java_library(name = 'util',
  dependencies = [
    '3rdparty/main/org.slf4j:slf4j',
    '3rdparty/war/org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.0_spec',
    '3rdparty/war/javax.servlet:javax.servlet-api',
  ],
  sources = globs('*.java'),
)
