
java_tests(name = 'util',
  sources = globs('*.java'),

  dependencies = [
    'modules/commons/src/java/com/fencedin/commons/model',
    'modules/commons/tests/java/com/fencedin/commons',
    '3rdparty/junit:junit',
    '3rdparty/org.slf4j:slf4j',
  ],

  resources=[
    'modules/commons/src/resources:log4j-properties',
  ],
)
