
java_library(name = 'backend',
  dependencies = [
    'modules/war/src/java/com/organization/backend/pages',
    '3rdparty/war/net.ftlines:wicket-cdi',
    '3rdparty/war/javax.servlet:servlet-api',
  ],
  sources = globs('*.java'),
)
