
java_library(name = 'rest',
  provides = artifact(
    org = 'com.fencedin.commons',
    name = 'rest',
    repo = public,
  ),

  dependencies = [
    'modules/commons/src/java/com/fencedin/commons/base',
    '3rdparty/org.json:json',
    '3rdparty/org.apache.commons:commons-lang3',
  ],

  sources = globs('*.java'),
)
