
java_library(name = 'model',
  provides = artifact(
    org = 'com.fencedin.commons',
    name = 'model',
    repo = public,
  ),
  dependencies = [
    'modules/commons/src/java/com/fencedin/commons/configuration',
    'modules/commons/src/java/com/fencedin/commons/base',
    #'3rdparty/org.greenrobot:greendao',
    '3rdparty/org.json:json',
    '3rdparty/de.undercouch:bson4jackson',
  ],
  sources = globs('*.java'),
)
