
resources(name='log4j-properties',
  sources=['log4j.properties'],
)

# For some reason, the log4j.properties file and its BUILD
# file must both be in a 3rd level directory for it to be
# interpreted by log4j.
