
java_tests(name = 'configuration',
  dependencies = [
    'modules/commons/src/java/com/fencedin/commons/configuration',
    'modules/commons/src/java/com/fencedin/commons/base',
    'modules/commons/tests/java/com/fencedin/commons',
    '3rdparty/junit:junit',
    '3rdparty/org.slf4j:slf4j',
    '3rdparty/org.json:json',
  ],
  sources = globs('*.java'),
  resources=[
    'modules/commons/src/resources:log4j-properties',
  ],
)
