
java_library(name = 'base',
  provides = artifact(
    org = 'com.fencedin.commons',
    name = 'base',
    repo = public,
  ),
  dependencies = [
    '3rdparty/org.apache.commons:commons-lang3',
    '3rdparty/org.json:json',
    '3rdparty/org.apache.httpcomponents:httpclient',
    '3rdparty/com.fasterxml.jackson.core:jackson-databind',
    '3rdparty/org.slf4j:slf4j',
  ],
  sources = globs('*.java'),
)
