
java_library(name = 'authentication',
  dependencies = [
    'modules/ejb/src/java/com/organization/backend/base',
    'modules/ejb/src/java/com/organization/backend/database',
    '3rdparty/main/com.organization.commons:base',
    '3rdparty/main/com.organization.commons:gis',
    '3rdparty/main/com.organization.commons:internal',
    '3rdparty/main/org.apache.commons:commons-codec',
    '3rdparty/main/org.json:json',
    '3rdparty/war/org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.0_spec',
    '3rdparty/war/javax.servlet:javax.servlet-api',
  ],
  sources = globs('*.java'),
)
