
# JVM binary that builds the libs used to create the EAR jar.
# --------------------------------------------------------------------------

jvm_binary(name = 'ear',
  basename = 'ear-ear',
  resources = [
    'modules/ear/src/application/META-INF',
  ],
)
